In [36]:
import pandas as pd # importo pandas para el tratamiento de data frames
import numpy as np  # import numpy para el manejo de arrays
from sklearn import linear_model # SKLEARN es la libreria de Machine Learning que implementa el algoritmo de Regresión Lineal

In [15]:
df = pd.read_csv('C:/Users/Fer/Documents/Fernando/archivospython/EjerciciosRegresion1.csv', sep=';')
df

PronosticoTempMax  PronosticoTempMin     Mes        Dia  DemandadeGas
0                14.3                3.6   Julio  Laborable          1465
1                16.3                1.2   Julio  Laborable          1499
2                 7.1                1.2   Julio  Laborable          1811
3                10.5                2.0   Julio  Laborable          1483
4                14.9                4.3   Julio    Feriado          1375
..                ...                ...     ...        ...           ...
57               14.9                2.3  Agosto  Laborable          1495
58               17.6                2.7  Agosto  Laborable          1475
59               10.3                4.1  Agosto    Feriado          1588
60                8.4                0.6  Agosto    Feriado          1833
61               11.3                2.1  Agosto  Laborable          1539

[62 rows x 5 columns]

In [38]:
#Elimino la varible dependiente
df1=df.drop('DemandadeGas',axis='columns')

#Transformo variable Dia categorica a Binaria
dummies = pd.get_dummies(df1['Dia'], prefix='Dia')
#dummies

#Borro la variable Dia Categorica y sumo la nueva binaria al dataset
#df1=df.drop('Sexo',axis='columns')
df1 = pd.concat([df1, dummies], axis=1)
df1=df1.drop('Dia',axis='columns')

df1

PronosticoTempMax  PronosticoTempMin     Mes  Dia_Feriado  Dia_Laborable
0                14.3                3.6   Julio        False           True
1                16.3                1.2   Julio        False           True
2                 7.1                1.2   Julio        False           True
3                10.5                2.0   Julio        False           True
4                14.9                4.3   Julio         True          False
..                ...                ...     ...          ...            ...
57               14.9                2.3  Agosto        False           True
58               17.6                2.7  Agosto        False           True
59               10.3                4.1  Agosto         True          False
60                8.4                0.6  Agosto         True          False
61               11.3                2.1  Agosto        False           True

[62 rows x 5 columns]

In [39]:
#Transformo variable Mes categorica a Binaria
dummies1 = pd.get_dummies(df1['Mes'], prefix='Dia')
#dummies1

#Borro la variable Dia Categorica y sumo la nueva binaria al dataset
#df1=df.drop('Sexo',axis='columns')
df1 = pd.concat([df1, dummies1], axis=1)
df1=df1.drop('Mes',axis='columns')

df1


PronosticoTempMax  PronosticoTempMin  Dia_Feriado  Dia_Laborable   
0                14.3                3.6        False           True  \
1                16.3                1.2        False           True   
2                 7.1                1.2        False           True   
3                10.5                2.0        False           True   
4                14.9                4.3         True          False   
..                ...                ...          ...            ...   
57               14.9                2.3        False           True   
58               17.6                2.7        False           True   
59               10.3                4.1         True          False   
60                8.4                0.6         True          False   
61               11.3                2.1        False           True   

    Dia_Agosto  Dia_Julio  
0        False       True  
1        False       True  
2        False       True  
3        False       True  
4        False       True  
..         ...        ...  
57        True      False  
58        True      False  
59        True      False  
60        True      False  
61        True      False  

[62 rows x 6 columns]

In [40]:
reg = linear_model.LinearRegression()
reg.fit(df1,df.DemandadeGas)

LinearRegression()

In [41]:
reg.coef_

array([-34.9917619 , -32.89223817,   3.30295435,  -3.30295435,
        17.53190165, -17.53190165])

In [42]:
reg.intercept_

2101.0517255071436

In [31]:
reg.predict([[15, 3, 0,1,0,1]])

c:\Users\Fer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1456.66372647])

In [32]:
reg.predict([[25, 3, 0,1,0,1]])

c:\Users\Fer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1106.74610745])

In [33]:
reg.predict([[15, -1, 0,1,0,1]])

c:\Users\Fer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1588.23267915])

In [35]:
reg.predict([[25, -1, 0,1,0,1]])

c:\Users\Fer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1238.31506014])